spring.application.name=flopbox

spring.security.enabled=false

# ===============================
# CONFIGURATION BASE DE DONNEES H2
# ===============================

# URL de connexion a la base (elle sera stockee en memoire vive)
spring.datasource.url=jdbc:h2:mem:flopboxdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate (JPA) : Creer et mettre a jour automatiquement les tables
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Afficher les requetes SQL dans la console (pratique pour debugger)
spring.jpa.show-sql=true

# Activer la console Web H2 pour voir vos donnees dans le navigateur
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.univ.sr2.flopbox=DEBUG