spring.application.name=flopbox


spring.security.enabled=false


# ===============================
# CONFIGURATION BASE DE DONNÉES H2
# ===============================

# URL de connexion à la base (elle sera stockée en mémoire vive)
spring.datasource.url=jdbc:h2:mem:flopboxdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate (JPA) : Créer et mettre à jour automatiquement les tables en fonction de vos @Entity
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Afficher les requêtes SQL dans la console (pratique pour débugger)
spring.jpa.show-sql=true

# Activer la console Web H2 pour voir vos données dans le navigateur
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.univ.sr2.flopbox=DEBUG